RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "The Trainer's School is excellent.\p"
	.string "If you study there, you could even\n"
	.string "become a Gym Leader.$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "Dor, the Gym Leader, really loves\n"
	.string "using Fairy-type Pokémon.\p"
	.string "She said they remind her of kids\n"
	.string "she'll never have.$"
