Route102_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route102_EventScript_ItemIceGem::
	finditem ITEM_ICE_GEM
	end

Route103_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

Route103_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route104_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route104_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route105_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route105_EventScript_ItemBugGem::
	finditem ITEM_BUG_GEM
	end

Route106_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route108_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

Route109_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route110_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route110_EventScript_ItemPsychicGem::
	finditem ITEM_PSYCHIC_GEM
	end

Route110_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route111_EventScript_ItemStardust::
	finditem ITEM_STARDUST
	end

Route111_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route112_EventScript_ItemSteelGem::
	finditem ITEM_STEEL_GEM
	end

Route113_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

Route113_EventScript_ItemAbilityCapsule::
	finditem ITEM_ABILITY_CAPSULE
	end

Route113_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route114_EventScript_ItemGimmighoulCoins_1::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route114_EventScript_ItemGimmighoulCoins_2::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route114_EventScript_ItemEnergyPowder::
	finditem ITEM_ENERGY_POWDER
	end

Route115_EventScript_ItemPoisonGem::
	finditem ITEM_POISON_GEM
	end

Route115_EventScript_ItemGimmighoulCoins_1::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route115_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

Route115_EventScript_ItemHealPowder::
	finditem ITEM_HEAL_POWDER
	end

Route115_EventScript_ItemGimmighoulCoins_2::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route115_EventScript_ItemRockGem::
	finditem ITEM_ROCK_GEM
	end

Route116_EventScript_ItemAbilityCapsule::
	finditem ITEM_ABILITY_CAPSULE
	end

Route116_EventScript_ItemThunderStone::
	finditem ITEM_THUNDER_STONE
	end

Route116_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route116_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route117_EventScript_ItemBugGem::
	finditem ITEM_BUG_GEM
	end

Route117_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route118_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemAbilityPatch::
	finditem ITEM_ABILITY_PATCH
	end

Route119_EventScript_ItemGimmighoulCoins_1::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route119_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route119_EventScript_ItemLeafStone::
	finditem ITEM_LEAF_STONE
	end

Route119_EventScript_ItemGimmighoulCoins_2::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route119_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemHyperPotion2::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemElixir2::
	finditem ITEM_ELIXIR
	end

Route120_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route120_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

Route120_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route120_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

Route120_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route121_EventScript_ItemGimmighoulCoins_1::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route121_EventScript_ItemManectite::
	finditem ITEM_MANECTITE
	end

Route121_EventScript_ItemGimmighoulCoins_2::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route122_EventScript_ItemPoisonGem::
	finditem ITEM_POISON_GEM
	end

Route123_EventScript_ItemGimmighoulCoins_1::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route123_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

Route123_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route123_EventScript_ItemHatterenite::
	finditem ITEM_HATTERENITE
	end

Route123_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route123_EventScript_ItemRevivalHerb::
	finditem ITEM_REVIVAL_HERB
	end

Route123_EventScript_ItemAltarianite::
	finditem ITEM_ALTARIANITE
	end

Route124_EventScript_ItemRedShard::
	finditem ITEM_RED_SHARD
	end

Route124_EventScript_ItemBlueShard::
	finditem ITEM_BLUE_SHARD
	end

Route124_EventScript_ItemYellowShard::
	finditem ITEM_YELLOW_SHARD
	end

Route125_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route125_EventScript_ItemSandacondanite::
	finditem ITEM_SANDACONDANITE
	end

Route126_EventScript_ItemKinglerite::
	finditem ITEM_KINGLERITE
	end

Route127_EventScript_ItemGimmighoulCoins_1::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route127_EventScript_ItemGimmighoulCoins_2::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route127_EventScript_ItemGimmighoulCoins_3::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route128_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route132_EventScript_ItemGimmighoulCoins_1::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route132_EventScript_ItemGimmighoulCoins_2::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route133_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route133_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

Route133_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

Route134_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

Route134_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

PetalburgCity_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

PetalburgCity_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

MauvilleCity_EventScript_ItemWaterGem::
	finditem ITEM_WATER_GEM
	end

MauvilleCity_GameCorner_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

LilycoveCity_EventScript_ItemAbilityCapsule::
	finditem ITEM_ABILITY_CAPSULE
	end

LilycoveCity_EventScript_ItemAmpharosite::
	finditem ITEM_AMPHAROSITE
	end

MossdeepCity_EventScript_ItemNetBall::
	finditem ITEM_NET_BALL
	end

FallarborTown_EventScript_ItemSoftSand::
	finditem ITEM_SOFT_SAND
	end

PetalburgWoods_EventScript_ItemLifeOrb::
	finditem ITEM_LIFE_ORB
	end

PetalburgWoods_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

PetalburgWoods_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

PetalburgWoods_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

PetalburgWoods_EventScript_ItemSilverPowder::
	finditem ITEM_SILVER_POWDER
	end

RusturfTunnel_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

RusturfTunnel_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

GraniteCave_1F_EventScript_ItemHeavyDutyBoots::
	finditem ITEM_HEAVY_DUTY_BOOTS
	end

GraniteCave_1F_EventScript_ItemRockGem::
	finditem ITEM_ROCK_GEM
	end

GraniteCave_B1F_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

GraniteCave_B2F_EventScript_ItemAggronite::
	finditem ITEM_AGGRONITE
	end

JaggedPass_EventScript_ItemGroundGem::
	finditem ITEM_GROUND_GEM
	end

FieryPath_EventScript_ItemFireStone::
	finditem ITEM_FIRE_STONE
	end

FieryPath_EventScript_ItemFireGem::
	finditem ITEM_FIRE_GEM
	end

MeteorFalls_1F_1R_EventScript_ItemMoonStone::
	finditem ITEM_MOON_STONE
	end

MeteorFalls_1F_1R_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

MeteorFalls_1F_1R_EventScript_ItemDragonGem::
	finditem ITEM_DRAGON_GEM
	end

MeteorFalls_B1F_2R_EventScript_ItemDragonFang::
	finditem ITEM_DRAGON_FANG
	end

MeteorFalls_B1F_2R_EventScript_ItemSalamencite::
	finditem ITEM_SALAMENCITE
	end

NewMauville_Inside_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

NewMauville_Inside_EventScript_ItemAbilityPatch::
	finditem ITEM_ABILITY_PATCH
	end

NewMauville_Inside_EventScript_ItemThunderStone::
	finditem ITEM_THUNDER_STONE
	end

NewMauville_Inside_EventScript_ItemElectricGem::
	finditem ITEM_ELECTRIC_GEM
	end

NewMauville_Inside_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

NewMauville_Inside_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

AbandonedShip_Rooms_1F_EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

AbandonedShip_Rooms_B1F_EventScript_ItemDuskStone::
	finditem ITEM_DUSK_STONE
	end

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall::
	finditem ITEM_DIVE_BALL
	end

AbandonedShip_Rooms2_1F_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey::
	finditem ITEM_STORAGE_KEY
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall::
	finditem ITEM_LUXURY_BALL
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemSlowbronite::
	finditem ITEM_SLOWBRONITE
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner::
	finditem ITEM_SCANNER
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone::
	finditem ITEM_WATER_STONE
	end

SafariZone_North_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

SafariZone_North_EventScript_ItemKangaskhanite::
	finditem ITEM_KANGASKHANITE
	end

SafariZone_Southwest_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

SafariZone_Northeast_EventScript_ItemMedichamite::
	finditem ITEM_MEDICHAMITE
	end

SafariZone_Southeast_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

MtPyre_2F_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

MtPyre_3F_EventScript_ItemSpellTag::
	finditem ITEM_SPELL_TAG
	end

MtPyre_4F_EventScript_ItemSeaIncense::
	finditem ITEM_SEA_INCENSE
	end

MtPyre_5F_EventScript_ItemGhostGem::
	finditem ITEM_GHOST_GEM
	end

MtPyre_6F_EventScript_ItemHeartScale::
	finditem ITEM_HEART_SCALE
	end

MtPyre_6F_EventScript_ItemGrimmsnarlite::
	finditem ITEM_GRIMMSNARLITE
	end

MtPyre_Exterior_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

MtPyre_Summit_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

MtPyre_Summit_EventScript_ItemTwistedSpoon::
	finditem ITEM_TWISTED_SPOON
	end

AquaHideout_B1F_EventScript_ItemDarkGem::
	finditem ITEM_DARK_GEM
	end

AquaHideout_B1F_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL
	end

AquaHideout_B1F_EventScript_ItemSharpedonite::
	finditem ITEM_SHARPEDONITE
	end

AquaHideout_B1F_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

AquaHideout_B2F_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

AquaHideout_B2F_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL      // Unused
	end

Route119_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route119_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

Route119_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

ShoalCave_LowTideInnerRoom_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal::
	finditem ITEM_ICE_HEAL
	end

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce::
	finditem ITEM_NEVER_MELT_ICE
	end

ShoalCave_LowTideIceRoom_EventScript_ItemGlalitite::
	finditem ITEM_GLALITITE
	end

SeafloorCavern_Room5_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

SeafloorCavern_Room7_EventScript_ItemLaprasite::
	finditem ITEM_LAPRASITE
	end

Route110_TrickHousePuzzle1_EventScript_ItemFireGem::
	finditem ITEM_FIRE_GEM
	end

Route110_TrickHousePuzzle2_EventScript_ItemIceGem::
	finditem ITEM_ICE_GEM
	end

Route110_TrickHousePuzzle2_EventScript_ItemWaterGem::
	finditem ITEM_WATER_GEM
	end

Route110_TrickHousePuzzle3_EventScript_ItemGhostGem::
	finditem ITEM_GHOST_GEM
	end

Route110_TrickHousePuzzle3_EventScript_ItemGrassGem::
	finditem ITEM_GRASS_GEM
	end

Route110_TrickHousePuzzle4_EventScript_ItemSteelGem::
	finditem ITEM_STEEL_GEM
	end

Route110_TrickHousePuzzle6_EventScript_ItemFairyGem::
	finditem ITEM_FAIRY_GEM
	end

Route110_TrickHousePuzzle7_EventScript_ItemElectricGem::
	finditem ITEM_ELECTRIC_GEM
	end

Route110_TrickHousePuzzle8_EventScript_ItemDragonGem::
	finditem ITEM_DRAGON_GEM
	end

VictoryRoad_1F_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

VictoryRoad_1F_EventScript_ItemMachampite::
	finditem ITEM_MACHAMPITE
	end

VictoryRoad_1F_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

VictoryRoad_B1F_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

VictoryRoad_B2F_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

ArtisanCave_B1F_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

ArtisanCave_1F_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

MagmaHideout_1F_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

MagmaHideout_2F_1R_EventScript_ItemCharcoal::
	finditem ITEM_CHARCOAL
	end

MagmaHideout_2F_2R_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

MagmaHideout_2F_2R_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

MagmaHideout_3F_1R_EventScript_ItemBigNugget::
	finditem ITEM_BIG_NUGGET
	end

MagmaHideout_3F_2R_EventScript_ItemGimmighoulCoins::
	@ finditem ITEM_GIMMIGHOUL_COIN
	goto Common_EventScript_ItemGimmighoulCoins
	end

MagmaHideout_4F_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

MagmaHideout_4F_EventScript_ItemCameruptite::
	finditem ITEM_CAMERUPTITE
	end

MagmaHideout_3F_3R_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

EverGradeCity_EventScript_ItemAudinite::
	finditem ITEM_AUDINITE
	end

CaveOfOrigin_1F_EventScript_ItemSablenite::
	finditem ITEM_SABLENITE
	end

SkyPillar_Outside_EventScript_ItemFlyingGem::
	finditem ITEM_FLYING_GEM
	end

Common_EventScript_FindItem::
	callnative GetObjectEventTrainerRangeFromTemplate
	finditem VAR_RESULT
	end

Common_EventScript_ItemGimmighoulCoins::
	checkitem ITEM_AMULET_COIN
	goto_if_eq VAR_RESULT, TRUE, Common_EventScript_ItemGimmighoulCoins_50
	goto Common_EventScript_ItemGimmighoulCoins_20
	end

Common_EventScript_ItemGimmighoulCoins_20::
	random 6
	addvar VAR_RESULT, 15
	finditem ITEM_GIMMIGHOUL_COIN, VAR_RESULT
	end

Common_EventScript_ItemGimmighoulCoins_50::
	random 11
    addvar VAR_RESULT, 40
	finditem ITEM_GIMMIGHOUL_COIN, VAR_RESULT
	end
